export default[
    {
        id:1,
        img:"layer1.png",
        rating:"4.5",
        reviewCount:3,
        location:"offline",
        title:"Life with queen elizabeth",
        price:140,
        openSpots: 3,
    },
    {
        id:2,
        img:"mountain-bike.png",
        rating:"4.5",
        reviewCount:3,
        location:"offline",
        title:"Life with queen elizabeth",
        price:140,
        openSpots: 0,
    },
    {
        id:3,
        img:"wedding-photography.png",
        rating:"4.5",
        reviewCount:3,
        location:"offline",
        title:"Life with queen elizabeth",
        price:140,
        openSpots: 20,
    },
    {
        id:4,
        img:"layer1.png",
        rating:"4.5",
        reviewCount:3,
        location:"online",
        title:"Life with queen elizabeth",
        price:140,
        openSpots: 24,
    },
    {
        id:5,
        img:"wedding-photography.png",
        rating:"4.5",
        reviewCount:3,
        location:"online",
        title:"Life with queen elizabeth",
        price:140,
        openSpots: 10,
    },
    {
        id:6,
        img:"mountain-bike.png",
        rating:"4.5",
        reviewCount:3,
        location:"offline",
        title:"Life with queen elizabeth",
        price:140,
        openSpots: 30,
    }
]
